INSERT INTO glossary_entries (phrase, normalized_phrase, language, threshold, team_id, category_id, root_cause_id, actionable_flag, notes, active)
VALUES
('Nevyhovuje', 'nevyhovuje', 'cs', 0.95,
 (SELECT id FROM teams WHERE `key`='CUSTOMER'),
 (SELECT id FROM categories WHERE `key`='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE `key`='USER_WRONG_CHOICE'),
 0,
 'Čistě obecná fráze – neakční.', 1),
('Nevhodný dárek', 'darek nevhodny', 'cs', 0.95,
 (SELECT id FROM teams WHERE `key`='CUSTOMER'),
 (SELECT id FROM categories WHERE `key`='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE `key`='USER_WRONG_CHOICE'),
 0,
 'Vrácení dárku – neakční.', 1),
('Objednal jsem omylem', 'jsem objednal omylem', 'cs', 0.90,
 (SELECT id FROM teams WHERE `key`='CUSTOMER'),
 (SELECT id FROM categories WHERE `key`='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE `key`='USER_DUPLICATE_ORDER'),
 0,
 'Duplicitní / chybná objednávka.', 1),
('Rosszul választottam', 'rosszul valasztottam', 'hu', 0.90,
 (SELECT id FROM teams WHERE `key`='CUSTOMER'),
 (SELECT id FROM categories WHERE `key`='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE `key`='USER_WRONG_CHOICE'),
 0,
 'Maďarsky – vybral jsem špatně.', 1),
('Ordered by mistake', 'by mistake ordered', 'en', 0.90,
 (SELECT id FROM teams WHERE `key`='CUSTOMER'),
 (SELECT id FROM categories WHERE `key`='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE `key`='USER_WRONG_CHOICE'),
 0,
 'Anglický omyl.', 1),
('Too late delivery', 'delivery late too', 'en', 0.90,
 (SELECT id FROM teams WHERE `key`='LOGISTICS'),
 (SELECT id FROM categories WHERE `key`='LOGISTICS_DELIVERY'),
 (SELECT id FROM root_causes WHERE `key`='LOGI_LATE_DELIVERY'),
 1,
 'Automatické označení pozdní dopravy.', 1);
