INSERT INTO glossary_entries (phrase, normalized_phrase, language, threshold, team_id, category_id, root_cause_id, actionable_flag, notes, active)
VALUES
('Nevyhovuje', 'nevyhovuje', 'cs', 0.95,
 (SELECT id FROM teams WHERE key='CUSTOMER'),
 (SELECT id FROM categories WHERE key='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE key='USER_WRONG_CHOICE'),
 FALSE,
 'Čistě obecná fráze – neakční.', TRUE),
('Nevhodný dárek', 'darek nevhodny', 'cs', 0.95,
 (SELECT id FROM teams WHERE key='CUSTOMER'),
 (SELECT id FROM categories WHERE key='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE key='USER_WRONG_CHOICE'),
 FALSE,
 'Vrácení dárku – neakční.', TRUE),
('Objednal jsem omylem', 'jsem objednal omylem', 'cs', 0.90,
 (SELECT id FROM teams WHERE key='CUSTOMER'),
 (SELECT id FROM categories WHERE key='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE key='USER_DUPLICATE_ORDER'),
 FALSE,
 'Duplicitní / chybná objednávka.', TRUE),
('Rosszul választottam', 'rosszul valasztottam', 'hu', 0.90,
 (SELECT id FROM teams WHERE key='CUSTOMER'),
 (SELECT id FROM categories WHERE key='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE key='USER_WRONG_CHOICE'),
 FALSE,
 'Maďarsky – vybral jsem špatně.', TRUE),
('Ordered by mistake', 'by mistake ordered', 'en', 0.90,
 (SELECT id FROM teams WHERE key='CUSTOMER'),
 (SELECT id FROM categories WHERE key='CUSTOMER_PREFERENCE'),
 (SELECT id FROM root_causes WHERE key='USER_WRONG_CHOICE'),
 FALSE,
 'Anglický omyl.', TRUE),
('Too late delivery', 'delivery late too', 'en', 0.90,
 (SELECT id FROM teams WHERE key='LOGISTICS'),
 (SELECT id FROM categories WHERE key='LOGISTICS_DELIVERY'),
 (SELECT id FROM root_causes WHERE key='LOGI_LATE_DELIVERY'),
 TRUE,
 'Automatické označení pozdní dopravy.', TRUE);
