INSERT INTO teams (key, name, description, prompt_definition, position) VALUES
('CONTENT', 'Content & Produktová stránka', 'Zodpovídá za přesnost popisků, parametrů a UX na webu.', 'Řeší chyby v popisu, chybějící parametry, kompatibilitu, varování a UX prezentaci produktu.', 1),
('QUALITY', 'Kvalita produktu', 'Řeší vady produktu, chybějící příslušenství a odlišné revize.', 'Posuď, zda je vrácení kvůli vadnému kusu, nekvalitnímu zpracování nebo nekompletnímu balení.', 2),
('LOGISTICS', 'Logistika & Fulfilment', 'Zodpovídá za dopravu, balení a správnost expedice.', 'Patří sem pozdní doručení, záměny položek a poškození při přepravě.', 3),
('CUSTOMER', 'Zákazník / změna názoru', 'Vrácení bez akční příčiny na naší straně.', 'Použij pokud zákazník jen změnil názor, zvolil špatně nebo nepotřebuje produkt.', 4);

INSERT INTO categories (team_id, key, name, description, prompt_definition, position) VALUES
((SELECT id FROM teams WHERE key='CONTENT'), 'CONTENT_MISINFORMATION', 'Chybná nebo chybějící informace', 'Popis, parametry nebo upozornění na webu jsou špatné či chybí.', 'Hledej formulace typu nepasuje, chybí funkce, není zmíněna montáž.', 1),
((SELECT id FROM teams WHERE key='CONTENT'), 'CONTENT_EXPECTATION', 'Nesplněné očekávání', 'Marketing a UX slibují něco jiného (barva, hlučnost, fotky).', 'Pokud zákazník zmiňuje vizuální rozdíl, hlučnost nebo varianty.', 2),
((SELECT id FROM teams WHERE key='QUALITY'), 'QUALITY_DEFECT', 'Vadné kusy', 'Produkt nefunguje, rozbíjí se nebo je nekompletní přímo od výrobce.', 'Když nejde zapnout, chybí části, je použitý.', 1),
((SELECT id FROM teams WHERE key='QUALITY'), 'QUALITY_BUILD', 'Špatné zpracování', 'Hlučnost, bezpečnost, podvodné vrácené kusy.', 'Pokud se projevuje špatné zpracování bez chyby v popisu.', 2),
((SELECT id FROM teams WHERE key='LOGISTICS'), 'LOGISTICS_DELIVERY', 'Doručení', 'Pozdní doručení nebo nedodržení slíbeného termínu.', 'Pokud zákazník výslovně zmiňuje zpoždění, čekání, musel koupit jinde.', 1),
((SELECT id FROM teams WHERE key='LOGISTICS'), 'LOGISTICS_PACKING', 'Chyby při expedici', 'Špatná varianta, chybějící kus, poškození během přepravy.', 'Zaměř se na výměnu barev, poškození krabice, otevřené balení.', 2),
((SELECT id FROM teams WHERE key='CUSTOMER'), 'CUSTOMER_PREFERENCE', 'Změna názoru', 'Omyl, nevhodný dárek, prostě už nechce.', 'Jasně osobní důvody bez chyby na naší straně.', 1),
((SELECT id FROM teams WHERE key='CUSTOMER'), 'CUSTOMER_SIZE', 'Velikost a preference', 'Velikost, rozměry, barva jen osobní preference.', 'Pokud není zmínka o chybě v popisu a jde jen o vkus nebo pocit.', 2);

INSERT INTO root_causes (team_id, category_id, key, name, description, prompt_definition, position) VALUES
((SELECT id FROM teams WHERE key='CONTENT'), (SELECT id FROM categories WHERE key='CONTENT_MISINFORMATION'), 'CONTENT_WRONG_DESCRIPTION', 'Chybný popis parametru', 'Na webu je nepravdivý údaj (materiál, funkce, kompatibilita).', 'Případy kdy zákazník říká, že něco slibujete a není to pravda.', 1),
((SELECT id FROM teams WHERE key='CONTENT'), (SELECT id FROM categories WHERE key='CONTENT_MISINFORMATION'), 'CONTENT_MISSING_CRUCIAL_INFO', 'Chybějící důležité upozornění', 'Není zmíněná montáž, omezení funkce nebo potřeba příslušenství.', 'Zákazník narazil na zásadní omezení, které web neříká.', 2),
((SELECT id FROM teams WHERE key='CONTENT'), (SELECT id FROM categories WHERE key='CONTENT_MISINFORMATION'), 'CONTENT_COMPATIBILITY_FIT', 'Špatná kompatibilita', 'Neodpovídá zařízení, velikosti nebo modelu i přes deklaraci.', 'Hodí se na hlášky typu nepasuje na iPad, jiný konektor.', 3),
((SELECT id FROM teams WHERE key='CONTENT'), (SELECT id FROM categories WHERE key='CONTENT_EXPECTATION'), 'CONTENT_DIMENSION_SIZE', 'Rozměry a fyzická velikost', 'Rozměr nebo délka neodpovídají očekávání a je to problém obsahu.', 'Např. "krátký kabel" pokud deklarujete jinou délku.', 1),
((SELECT id FROM teams WHERE key='CONTENT'), (SELECT id FROM categories WHERE key='CONTENT_EXPECTATION'), 'CONTENT_NOISE_EXPECTATION', 'Hlučnost vs. marketing', 'Uvedeno tiché, ale reálně hlučné.', 'Zákazník explicitně srovnává s tvrzením na webu.', 2),
((SELECT id FROM teams WHERE key='CONTENT'), (SELECT id FROM categories WHERE key='CONTENT_EXPECTATION'), 'CONTENT_COLOR_APPEARANCE', 'Barva / vzhled neodpovídá', 'Fotka, render nebo popis zkresluje barvu / vzhled.', 'Pokud píše že barva jiná než na obrázku.', 3),
((SELECT id FROM teams WHERE key='CONTENT'), (SELECT id FROM categories WHERE key='CONTENT_EXPECTATION'), 'CONTENT_VARIANT_PRESENTATION', 'Špatná prezentace variant', 'Existují varianty (barvy) ale zákazník je neviděl.', 'Použij při zmínce že našel jinou barvu až po nákupu.', 4),
((SELECT id FROM teams WHERE key='QUALITY'), (SELECT id FROM categories WHERE key='QUALITY_DEFECT'), 'PROD_DEFECTIVE', 'Vadný kus', 'Produkt nefunguje, vypíná se, nesplní základní funkci.', 'Vady po pár dnech, nejde zapnout, nefunguje senzor.', 1),
((SELECT id FROM teams WHERE key='QUALITY'), (SELECT id FROM categories WHERE key='QUALITY_DEFECT'), 'PROD_INCOMPLETE_INBOX', 'Chybí příslušenství', 'V balení nejsou všechny části.', 'Chybí sítko, šroubky, díly.', 2),
((SELECT id FROM teams WHERE key='QUALITY'), (SELECT id FROM categories WHERE key='QUALITY_DEFECT'), 'PROD_WRONG_REVISION', 'Špatná revize / použitý kus', 'Došel jiný model, repas, nebo evidentně použitý kus.', 'Zákazník zmiňuje opotřebení, jiný modelový rok.', 3),
((SELECT id FROM teams WHERE key='QUALITY'), (SELECT id FROM categories WHERE key='QUALITY_BUILD'), 'PROD_BUILD_ISSUE', 'Špatné zpracování / hlučnost', 'Vadné větráky, nebezpečné hrany, nestabilní konstrukce.', 'Když produkt sám o sobě je nekvalitní bez souvislosti s popisem.', 1),
((SELECT id FROM teams WHERE key='QUALITY'), (SELECT id FROM categories WHERE key='QUALITY_BUILD'), 'PROD_PACKAGING_DAMAGE', 'Poškozený produkt od dodavatele', 'Krabice či produkt dorazil poškozený ještě před expedicí.', 'Rozbitý uvnitř originálního balení, ne vinou přepravy.', 2),
((SELECT id FROM teams WHERE key='LOGISTICS'), (SELECT id FROM categories WHERE key='LOGISTICS_DELIVERY'), 'LOGI_LATE_DELIVERY', 'Pozdní doručení', 'Doručení přišlo později než slíbeno.', 'Hlášky typu "musel jsem koupit jinde".', 1),
((SELECT id FROM teams WHERE key='LOGISTICS'), (SELECT id FROM categories WHERE key='LOGISTICS_PACKING'), 'LOGI_WRONG_ITEM_VARIANT', 'Špatná varianta / barva', 'Expedována jiná barva či model než objednáno.', 'Zákazník dostal jinou variantu, i když web uvádí správnou.', 1),
((SELECT id FROM teams WHERE key='LOGISTICS'), (SELECT id FROM categories WHERE key='LOGISTICS_PACKING'), 'LOGI_DAMAGED_ON_ARRIVAL', 'Poškození během přepravy', 'Poškozená krabice, rozbitý produkt během doručení.', 'Zákazník popisuje poničené balení při převzetí.', 2),
((SELECT id FROM teams WHERE key='LOGISTICS'), (SELECT id FROM categories WHERE key='LOGISTICS_PACKING'), 'LOGI_INCOMPLETE_DELIVERY', 'Chybějící část zásilky', 'V balíku chyběla část objednávky.', 'Použij pokud dorazila jen část setu nebo příslušenství.', 3),
((SELECT id FROM teams WHERE key='LOGISTICS'), (SELECT id FROM categories WHERE key='LOGISTICS_PACKING'), 'LOGI_OPEN_BOX', 'Otevřené / použité balení', 'Produkt přišel rozbalený, ale měl být nový.', 'Zákazník hlásí rozlepenou pečeť nebo použité příslušenství.', 4),
((SELECT id FROM teams WHERE key='CUSTOMER'), (SELECT id FROM categories WHERE key='CUSTOMER_PREFERENCE'), 'USER_WRONG_CHOICE', 'Špatná volba', 'Zákazník si objednal omylem, nevhodný dárek.', 'Použij pro hlášky omylem objednáno, nevhodný dárek.', 1),
((SELECT id FROM teams WHERE key='CUSTOMER'), (SELECT id FROM categories WHERE key='CUSTOMER_PREFERENCE'), 'USER_NO_LONGER_NEEDED', 'Už nepotřebuje', 'Koupil jinde, už to nepotřebuje.', 'Čistě změna situace, bez naší chyby.', 2),
((SELECT id FROM teams WHERE key='CUSTOMER'), (SELECT id FROM categories WHERE key='CUSTOMER_PREFERENCE'), 'USER_DUPLICATE_ORDER', 'Duplicitní objednávka', 'Objednal dvakrát nebo má doma jiný kus.', 'Texty typu objednal jsem dvakrát.', 3),
((SELECT id FROM teams WHERE key='CUSTOMER'), (SELECT id FROM categories WHERE key='CUSTOMER_SIZE'), 'USER_SIZE_PREF_ONLY', 'Velikost nevyhovuje (bez chyby)', 'Rozměr nesedí z osobních preferencí, bez zmínky o chybě.', 'Zákazník neobviňuje popis, jen mu to nesedí.', 1),
((SELECT id FROM teams WHERE key='CUSTOMER'), (SELECT id FROM categories WHERE key='CUSTOMER_SIZE'), 'USER_PRICE_ELSEWHERE', 'Koupil jinde levněji', 'Produkt vrací kvůli lepší nabídce.', 'Použij když explicitně zmiňuje nákup jinde kvůli ceně.', 2);
